engines:
  rubocop:
    enabled: true
    #checks:
    #	Rubocop/Metrics/ClassLength:
    #  	enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - ruby:
          mass_threshold: 30
ratings:
  paths:
  - lib/**
  - "**.rb"
exclude_paths:
exclude_paths:
- lib/assets/**/*
- test/**/*
